runSTR: runSTR.o Config.o Features.o HaarFeature.o HaarFeatures.o HistogramFeatures.o HistogramFeatures.o ImageRep.o LaRank.o MultiFeatures.o RawFeatures.o Sampler.o Tracker.o GraphUtils/GraphUtils.o

LDLIBS = -lopencv_core -lopencv_highgui -lopencv_imgproc -lm -lstdc++

CPPFLAGS = -I/usr/include/eigen3 
